### ISSUE TITLE
Incompatible with Rust std

### ISSUE THREAD

**Issue by js2xxx** [nbdd0121/unwinding#20]
The structure of the raw exception in [Rust std](https://github.com/rust-lang/rust/blob/master/library/panic_unwind/src/gcc.rs#L55) is different from the one in [this crate](https://github.com/nbdd0121/unwinding/blob/trunk/src/panic.rs#L26), which prevents this crate from catching panics raised in std. Or is it on purpose?
Also, the `canary` field in std's implementation seems almost inaccessible from this crate, so is it possible to add an "std" feature to forward this crate's public APIs to std?

**Comment by nbdd0121** [comment]
The feature provided is intended to be used on programs/platforms where std is not available.

That said, I should have updated the crate to add the canary to detect misuse.

**Comment by js2xxx** [comment]
Thanks a lot! I'll have to set up a feature gate for selecting the panic implementation in my library crate.
