### ISSUE TITLE
Bump version and release to crates.io for riscv32 fixes

### ISSUE THREAD

**Issue by xobs** [nbdd0121/unwinding#22]
I'd like to incorporate the fixes that were part of cf89c1934cc9d16606eec2de2d9b25c3079fc5b4 into libstd. For now I have a local patch pointing at this repo, but at some point I'd like to be able to use the fix when building with upstream Rust.

To that end, I'd like to have this issue closed once a version is released with the incorporated fixes so that I don't lose track of the change.

**Comment by nbdd0121** [comment]
I plan to do the next point release after `c_unwind` feature stabilisation.

**Comment by xobs** [comment]
Thanks for the update. For refrence, tracking issue is https://github.com/rust-lang/rust/issues/74990 and the stabilization PR appears to be https://github.com/rust-lang/rust/pull/116088

**Comment by lylythechosenone** [comment]
@nbdd0121 it might be worth a new version even without stabilization, given that the crate is currently broken (#28), and also given the numerous fixes since the last version.

**Comment by nbdd0121** [comment]
A new version is published
