### ISSUE TITLE
bare-metal link-script modification with rust-lld

### ISSUE THREAD

**Issue by tpdenk** [nbdd0121/unwinding#6]
> Modify the linker script by
> 
> /\* Inserting these two lines \*/
> . = ALIGN(8);
> PROVIDE(__eh_frame = .);
> /\* before .eh_frame rule \*/
> .eh_frame : { KEEP (\*(.eh_frame)) \*(.eh_frame.\*) }

How would I do this with rust-lld?

In my `target.json`, I tried to use `linker: ld` and then used the feature `fde-gnu-eh-frame-hdr` instead of `fde-static`, but that gives me an error saying that ld doesn't know the argument `-Wl,--as-needed`.
That is why I believe I am stuck with `rust-lld` with flavour `gnu`, but that doesn't seem to recognise the `__GNU_EH_FRAME_HDR`.
Is there a way I can make this work? Modifying the link script that rust-lld uses or with a `build.rs` or similar?

<details>
<summary>my target.json</summary>
<pre lang="json">
{
  "llvm-target": "x86_64-unknown-none",
  "arch": "x86_64",
  "os": "none",
  "executables": true,
  "linker-flavor": "ld.lld",
  "linker": "rust-lld",
  "panic-strategy": "unwind",
  ...
}
</pre>
</details>

**Comment by nbdd0121** [comment]
Linker script is specified by passing argument to the linker, this can be done in RUSTFLAGS with `-Clink-args=-T<path to linker script>`.

**Comment by nbdd0121** [comment]
The `-Wl,--as-needed` error is triggered probably because wrong linker-flavour is set. If you change linker to `ld` then `linker-flavor` should be set to `ld` as well.

**Comment by tpdenk** [comment]
> Linker script is specified by passing argument to the linker, this can be done in RUSTFLAGS with `-Clink-args=-T<path to linker script>`.

I don't have a linker script.

> The `-Wl,--as-needed error` is triggered probably because wrong linker-flavour is set. If you change linker to `ld` then `linker-flavor` should be set to `ld` as well.

Just did that, the message is now `ld: unknown option: --as-needed`.
(I am on Mac, I think this is a good time mentioning that).
Now, I found https://github.com/rust-lang/rust/issues/34282 , and it would really suck if that was the end.
I also found https://github.com/rust-lang/rust/issues/52684 , and tried to specify pre-link-args in my own target.json, without the as-needed, but it still tries to invoke the linker with that.

Do you have any ideas here? I'd really like to avoid having to write my own linker script, as I have no experience with that at all.

**Comment by tpdenk** [comment]
Friendly ping

**Comment by nbdd0121** [comment]
If you are cross compiling you would need a cross compiling toolchain, you can't use your host toolchain. There are also plenty of resources online about linker scripts, e.g. https://wiki.osdev.org/Linker_Scripts. If you are compiling for baremetal targets I don't see how linker script could be avoided.

**Comment by tpdenk** [comment]
For the kernel, I was following [phil-opp's OS](http://os.phil-opp.com/), which lets Rust take care of building the kernel, and then wraps it into a bios image. However, the linker errors occur at building in the "first" stage, before the second stage can wrap the executable into an image. No link script before the second stage.

https://github.com/martimos/kernel is the project. It uses a custom target definition. Also notice the `.cargo/config.toml`.

From your comment I read that I'll just have to create a linker script. Do you have any resource that shows a simple one for Rust? Maybe even an example?

**Comment by nbdd0121** [comment]
If not specified, the default linker script is used. Generally it's very bad practice to use the default one, because the default one is not intended for baremetal apps.

If you have a GNU linker you can just use `ld --verbose` to get your default linker script.

**Comment by nbdd0121** [comment]
Those toy kernels can get away with that, but as soon as you start to do paging etc, you *will* need to control where your kernel is located precisely.

**Comment by tpdenk** [comment]
I got back to this with more stuff @nbdd0121 (and I've seen #8).

I understand that most of the problems that arise can not be fixed by your crate, however I wonder what the intended use for the `fde-custom` feature was? Where would I get the addresses from, and if from a symbol, why wouldn't I use `fde-static` or another one instead?

**Comment by nbdd0121** [comment]
Reason can be found in the PR that introduced it: #12
