### ISSUE TITLE
Symbol resolution

### ISSUE THREAD

**Issue by stevefan1999-personal** [nbdd0121/unwinding#7]
What should I do to resolve the stack trace to something readable, especially when running inside a bare metal (for me actually, a toy kernel)?

**Comment by nbdd0121** [comment]
That requires access to debug information, which is not loadable part of ELF (as opposed to `eh_frame`, which is). This means that it can be difficult to access for baremetal application.

If you toy kernel can access its own ELF file (either you load the raw ELF file using bootloader, or if you toy kernel has file systems then it might be able to load itself), then you can try to use `addr2line` crate to parse it. This can be difficult though.

Another approach is to dump the symbol addresses into a table and link it with your kernel, so your kernel can use a lookup table to resolve addresses (Linux kernel uses this approach, check out Kallsyms).

If you don't need to have symbol names resolved online, you can also just do it offline using the addr2line tool on your dev machine.
