### ISSUE TITLE
Fails to compile on recent Rust nightlies

### ISSUE THREAD

**Issue by Gaelan** [nbdd0121/unwinding#9]
Looks like the LLVM 15 upgrade broke something:

```
   Compiling unwinding v0.1.4 (/private/tmp/unwinding)
inlinable function call in a function with debug info must have a !dbg location
  call void @_Unwind_Resume(ptr %40) #15
inlinable function call in a function with debug info must have a !dbg location
  call void @_Unwind_Resume(ptr %20) #15
inlinable function call in a function with debug info must have a !dbg location
  call void @_Unwind_Resume(ptr %50) #15
inlinable function call in a function with debug info must have a !dbg location
  call void @_Unwind_Resume(ptr %47) #15
LLVM ERROR: Broken module found, compilation aborted!
error: could not compile `unwinding`
```

I assume this is a rustc bug, so I've filed rust-lang/rust#101121 - but filing a bug here too, just in case.

**Comment by nbdd0121** [comment]
Yeah, it does look like that it is a rustc bug.

**Comment by tpdenk** [comment]
This is an LLVM bug. You can work around that by adding
```toml
[profile.dev]
debug = 0

[profile.release]
debug = 0
```

to your `Cargo.toml`.

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23101121.20.22unwinding.22.20crate.20fails.20to.20compile.20after.20LLVM.2015)).

@rustbot label -I-prioritize +P-high

**Comment by nbdd0121** [comment]
Issue upstream is resolved
